# Site settings
title: "Kirk .S. Agbenyegah"
email: savekirk@gmail.com
description: "Personal blog of Kirk .S. Agbenyegah."
baseurl: ""
url: "http://savekirk.com/"
title_description: "I'm a full stack developer with a mobile focus. I specialize in Android with Java, Kotlin and functional programming methods with Python, Clojure and Javascript. I have a track record of delivered software projects and happy clients; both as an individual contributor and as a tech lead. I boostrapped two companies and am the author of a number of mobile apps in the Android Playstore. I am currently based in Accra and I'm available for remote work. Besides software development, I enjoy meeting new people, reading/writing, and teaching. <br /><p>If you are interested in hiring me, want to discuss a future project, commission me to teach a workshop in your area, or anything else, please feel free to contact me by email</p>"
title_image: "https://drive.google.com/file/d/0Bx9MfNW9E3OCdDZyTE1VRFlaNjQ/view?usp=sharing"
google_analytics: "UA-20365477-4"
disqus_account: savekirk
github_repository: https://github.com/savekirk/savekirk.com
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: savekirk
github_username:  savekirk
linkedin_link: http://linkedin.com/in/savekirk
google_plus_link: 
stackoverflow_link: 
# Footer
footer_left: "Theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
